<?php

/**
 * PluginOsApplicationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOsApplicationTable extends DummyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOsApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOsApplication');
    }
}
