<?php

/**
 * PluginOsTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOsTokenTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOsTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOsToken');
    }
}