all:
  is_secure: true

index:
  credentials: [tck-onlinechoices-app]
edit:
  credentials: [tck-onlinechoices-app-edit]
new:
  credentials: [tck-onlinechoices-app-new]
delete:
  credentials: [tck-onlinechoices-app-del]
batchDelete:
  credentials: [tck-onlinechoices-app-del]
