# config/services.yml
dev:
    parameters:

all:
    parameters:

    services:
        api_oauth_service:
            class: ApiOAuthService
        api_payments_service:
            class: ApiPaymentsService
            calls:
                - ['setOAuthService', ['@api_oauth_service']]
                - ['setTranslationService', ['@api_translation_service']]
        api_carts_service:
            class: ApiCartsService
            calls:
                - ['setOAuthService', ['@api_oauth_service']]
                - ['setCartItemsService', ['@api_cartitems_service']]
                #- ['setCustomersService', ['@api_customers_service']]
        api_orders_service:
            class: ApiOrdersService
            calls:
                - ['setOAuthService', ['@api_oauth_service']]
        api_cartitems_service:
            class: ApiCartItemsService
            calls:
                - ['setOAuthService', ['@api_oauth_service']]
        #        - ['setManifestationsService', ['@api_manifestations_service']]
        api_actions_service:
            class: ApiActionsService
        api_translation_service:
            class: ApiTranslationService    
        api_events_service:
            class: ApiEventsService
            calls:
                - ['setApiManifestationsService', ['@api_manifestations_service']]
                - ['setTranslationService', ['@api_translation_service']]
                - ['setOAuthService', ['@api_oauth_service']]
        api_manifestations_service:
            class: ApiManifestationsService
            calls:
                - ['setTranslationService', ['@api_translation_service']]
                - ['setOAuthService', ['@api_oauth_service']]
                - ['setManifestationsService', ['@manifestations_service']] # from project

