OsToken:
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    token:
      type: string(255)
      notnull: true
    refresh_token:
      type: string(255)
      notnull: true
    expires_at:
      type: timestamp
      notnull: true
    os_application_id:
      type: integer
      notnull: true
    transaction_id:
      type: integer
      notnull: true
  indexes:
    os_token_token_idx:
      fields: [token]
  relations:
    Transaction:
      foreignType: one
      onDelete: CASCADE
      onUpdate: CASCADE
    OsApplication:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OsTokens
OsApplication:
  inheritance:
    extends: Dummy
    type: concrete
  columns:
    identifier:
      type: string(255)
      notnull: true
    secret:
      type: string(255)
      notnull: true
    user_id:
      type: integer
      notnull: true
    expires_at: timestamp
  indexes:
    os_application_identifier_secret_idx:
      fields: [identifier, secret]
  relations:
    User:
      local: user_id
      class: sfGuardUser
      foreignAlias: OsApplications
      onDelete: CASCADE
      onUpdate: CASCADE
